version: '3'

services:

  app:
    build: .
    restart: always
    command: ["sh", "./scripts/start_service.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ENV=no-debug  # set this to debug to start the flask debug server
      - POOL_SIZE=5   # if not debug, then this is the number of wsgi workers spawned

  tests:
    build: .
    command: pytest
    volumes:
      - .:/app
